# Generated by Django 5.1.1 on 2024-10-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ecommerce_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerce',
            name='price',
            field=models.PositiveIntegerField(default=1500000),
        ),
    ]
