# Generated by Django 5.1.1 on 2024-10-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ecommerce_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerce',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
